version: '3'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: agente
      MARIADB_USER_PASSWORD: MiClave
      MARIADB_DATABASE: NMAP
    volumes:
      - ./dockerImage/mariadb/entry:/docker-entrypoint-initdb.d
      - ./dockerImage/mariadb/config/99-ssl.cnf:/etc/mysql/mariadb.conf.d/99-ssl.cnf:ro
      - ./dockerImage/ssl:/etc/ssl-certs/
    expose:
      - "3306"
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
    ports:
      - 9093:80
    depends_on:
      - mariadb
  python:
    container_name: app
    build: ./dockerImage/python
    environment:
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_DATABASE: NMAP
      DB_HOST: mariadb
      DB_PORT: 3306
      PORT: 8080
      HOST: 0.0.0.0
      SECRET_KEY: 1337-H4xx0ry-0v3r-H3r3
    volumes:
      - ./dockerImage/ssl:/etc/ssl-certs/
  apache:
    container_name: apache
    image: httpd:latest
    ports:
     - 7777:443
    volumes:
     - ./dockerImage/apache/static:/usr/local/apache2/htdocs
     - ./dockerImage/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
     - ./dockerImage/apache/reverse.conf:/usr/local/apache2/conf/sites/reverse.conf
     - ./dockerImage/ssl:/etc/ssl-certs/